### ISSUE TITLE
편집일 때와 편집이 아닐 때 어떻게 화면을 보여줄 것인지

### ISSUE THREAD

**Issue by kuflower** [KUflower/Devnote#2]
마크다운 상태일 떄와 아닐 때, 코드 편집 모드일 때와 아닐 때 어떻게 전환하고 보여줄 것인지

**Comment by KUflower** [comment]
마크다운 상태일 떄와 아닐 때, 코드 편집 모드일 때와 아닐 때 어떻게 전환하고 보여줄 것인지
